### PR TITLE
Asynchronous invitation of found candidates enabled.

### LINKED ISSUE #528: Opportunities Platform - Ability to share to more than one user from Find/Member Search results
As an opportunity creator, I want to be able to go down the list of members and offer opportunities to more than one user without having to re-run the search.  Options for resolution: check-box beside members and a single share opportunity button, ability to click "Share Opportunity" button and remain on search results page.

### PR DESCRIPTION
**Pull request by lucbelliveau**
Also fixed reversed status message.  ie You have shared the opportunity 'username' with 'opportunity'.

fixes #528

### CODE REVIEW

**Comment by ToferC** [comment]
Hi @lucbelliveau - @Phanoix has pushed your commits to pre-prod, but the multi-select isn't working on our system.  Can you touch base with @Phanoix re: possible reasons for this?  Thanks!

**Comment by lucbelliveau** [comment]
Sure... is there an error @Phanoix ?

Also were the Elgg cache flushed?  Because of [ajax.js](https://github.com/tbs-sct/gcconnex/blob/967bf32fe2c71392681c53c4c9c9da867670a75c/mod/missions/views/default/js/mission-invite/ajax.js) the caches must be flushed...

**Comment by ToferC** [comment]
@Phanoix - can you confirm this?  It isn't working for me on pre-prod.  From Share Opportunity page, it redirects to Search for Opportunities after I click the "Share" button.  Thanks!

**Comment by Phanoix** [comment]
I just tested it using the regular members search and it worked (on pre-prod).

**Comment by ToferC** [comment]
This is live and works great from the Find Candidates Screen. @Phanoix - can you please enable the same functionality from hitting the Find button on an opportunity?  Thanks!

**Comment by Phanoix** [comment]
Looks like the that list works differently, using links instead of forms with buttons for the invitation action so the ajax invitation script will need to be adapted for that.

**Comment by ToferC** [comment]
Gotcha. @lucbelliveau - can you take point on that?

**Comment by lucbelliveau** [comment]
Sure - should I reopen this PR or create a new one?

**Comment by ToferC** [comment]
Let's say new one to keep it clean.

**Pull request merged**
