### PR TITLE
Fixing contact form language and adding the 'career' tab to gcconnex theme

### PR DESCRIPTION
**Pull request by piet0024**

### CODE REVIEW

**Comment by piet0024** [comment]
@Phanoix any idea why this wouldn't pass the travis test?

**Comment by Phanoix** [comment]
You didn't change anything it tests right now, so no idea why it decided to fail there.

**Comment by piet0024** [comment]
I also pulled from the main branch before I branched off (You were standing over my shoulder when it happened) to make sure I had the latest code too 😕

**Comment by Phanoix** [comment]
try getting it to run it again, just push something inconsequential.

**Comment by piet0024** [comment]
Pushed a new commit with comments let's see if this works

**Comment by piet0024** [comment]
🤔 Maybe if I rebase 🤔

**Pull request merged**
