### PR TITLE
Streaming wire page

### PR DESCRIPTION
**Pull request by piet0024**
If a user stays idle on the wire page it will notify them that there are new posts. It will then load the new posts through Ajax

### CODE REVIEW

**Comment by ToferC** [comment]
Just tested on pre-prod.  Still grabbing an extra wire post and duplicating it.  Also. please ensure that the streaming wire is also applied to the Newsfeed page.  Thanks!

**Comment by Phanoix** [comment]
The newsfeed is a very different feed and is most users' home page, so while some of the work done here can be reused we should approach a streaming newsfeed as a separate piece of work. It can't use the current API to fetch the feed and we'll need to consider server load impact more.

**Comment by ToferC** [comment]
Agreed on newsfeed. To clarify: streaming wire should also be on newsfeed
page.

**Comment by piet0024** [comment]
I made some changes to this so it should no longer create duplicates. Before it was comparing post text and now it is comparing GUIDs. The mod now also has a custom index widget for the newsfeed page that should function the same as the wire page.

**Comment by ToferC** [comment]
Tested and confirmed it works. On occasion the whole page will refresh
instead of just the widget. Also, the pop-up of new wire items is a bit
sudden. Might want to look at a smooth transition if it's not too much
work. Thanks!

**Pull request merged**
